units:
  # utilisation d'une variable d'environnement prédéfinie
  # pour masquer des infos ou conditionner les jobs
  image: $CI_REGISTRY_IMAGE/maven:3.8.5-openjdk-17-slim
  tags: [myusine]
  script:
    - mvn test
  artifacts:
    # les artifacts qui sont des fichiers untracked 
    # du point de vue de git
    # par défaut les artefacts injectés dans un job suivant 
    # seront dégagés par git clean
    # untracked: false
    # dlc de l'artifact
    expire_in: "1 hour"
    # chemin de prélèvement
    # - pour téléchargement depuis cetaines intefaces de Gitlab
    # - pour permettre de réinjecter l'artifact dans les jobs suivant
    paths:
      - "target/surefire-reports/TEST-*.xml"
    # gestion d'artefacts spéciaux (units, qualité, coverage ...)
    reports:
      junit: "target/surefire-reports/TEST-*.xml"
      

