# déplacement de l'image maven au niveau du pipeline lui même
# car cette image est centrale pour les jobs
image: $CI_REGISTRY_IMAGE/maven:3.8.5-openjdk-17-slim

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  # déplacer les dépédences installées à la racine du dépôt dans les containers
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


cache:
  # policy: pull-push
  # on ne nettoie pas les fichiers 'untracked' avec git clean
  untracked: true
  # when: on_success
  paths:
    - ".m2/repository"

stages:
  - test
  - coverage
  - quality

generate_cache:
  # exécution parrallèle pour générer 2 exemplaires du cache
  # en cas d'exécution de jobs concurents
  # on utilise cette clé sur un job dont le but de générer les dépendences 
  parallel: 2
  # .pre => stage caché qui est toujours exécuté avant les autres
  stage: .pre
  tags:
    - myusine
  script:
    - mvn compile

units:
  stage: test
  tags: [myusine]
  # variables:
  #   MY_VAR: my_value
  script:
    - mvn test
    - cat target/site/jacoco/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    expire_in: "1 hour"
    paths:
      - "target/surefire-reports/TEST-*.xml"
      - "target/site/jacoco/jacoco.xml"
      - "target/site/jacoco/index.html"
    reports:
      junit: "target/surefire-reports/TEST-*.xml"

.bullshit_job:
  stage: test
  tags:
    - myusine
  script:
    - sleep 25

coverage:
  stage: coverage
  needs: [units]
  image: haynes/jacoco2cobertura:1.0.7
  tags:
    - myusine
  script:
    - >
      python /opt/cover2cover.py 
      target/site/jacoco/jacoco.xml
      $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml

sonar:
  stage: quality
  tags:
    - myusine
  script:
    - >
      mvn clean test sonar:sonar
      -Dsonar.projectKey=myproject
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.qualitygate.wait=true
      -Dsonar.java.binaries=target
      -Dsonar.junit.reportPaths=target/surefire-reports
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      

