# liste ordonnée des étapes principales du pipeline
stages:
  - test
  - coverage

units:
  image: $CI_REGISTRY_IMAGE/maven:3.8.5-openjdk-17-slim
  stage: test
  tags: [myusine]
  script:
    - mvn test
    # il faut afficher le rapport de couverture qui comprend le total
    - cat target/site/jacoco/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    expire_in: "1 hour"
    paths:
      - "target/surefire-reports/TEST-*.xml"
      - "target/site/jacoco/jacoco.xml"
      - "target/site/jacoco/index.html"
    reports:
      junit: "target/surefire-reports/TEST-*.xml"

# exécution de plusieurs jobs dans un stage ==> exécution //
# "." : job désactivé
.bullshit_job:
  stage: test
  tags:
    - myusine
  script:
    - sleep 25

coverage:
  stage: coverage
  # optionnel: needs va pouvoir démarrer le job coverage 
  # dès que le job units terminé
  # même si le job bullshit n'est pas terminé
  needs: [units]
  image: haynes/jacoco2cobertura:1.0.7
  tags:
    - myusine
  script:
    - >
      python /opt/cover2cover.py 
      target/site/jacoco/jacoco.xml
      $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml
      

